# Generated by Django 4.1.2 on 2022-11-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruxlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'guruxlash',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255)),
                ('matn', models.TextField()),
                ('joylangan', models.DateTimeField(auto_now_add=True)),
                ('rasm', models.ImageField(upload_to='image/')),
                ('gurux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gurux', to='news.guruxlash')),
            ],
            options={
                'verbose_name_plural': 'post',
                'ordering': ['-joylangan'],
            },
        ),
    ]
