# Generated by Django 4.1.3 on 2022-11-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlovha', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('matn', models.TextField(blank=True, null=True)),
                ('rasm', models.ImageField(default='', upload_to='image/')),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('xizmat', models.CharField(blank=True, max_length=255, null=True)),
                ('joylangan', models.DateTimeField(auto_now_add=True)),
                ('vaqt', models.DateTimeField()),
            ],
            options={
                'ordering': ['-joylangan'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='matn2',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='matn3',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
