# Generated by Django 4.1.3 on 2022-11-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_portfolio_post_matn2_post_matn3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='matn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='matn2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='matn3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
